spring.application.name=PaperPilot
#server.port=9090
server.address=0.0.0.0
#database connect
spring.datasource.url=jdbc:mysql://localhost:3306/PaperPilot
spring.datasource.username=root
spring.datasource.password=rabbi1067

#database auto tables create korer jnne
spring.jpa.hibernate.ddl-auto= update


